# Change these first
owner: zbtechph # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Billing Portal
    url: https://billing.sulithosting.com
    type: globalping
    location: Philippines
  - name: WEB-US01
    url: $WEB_US01
  - name: WEB-US02
    url: $WEB_US02
  - name: WEB-SG01
    url: $WEB_SG01
  - name: WEB-NL01
    url: $WEB_NL01

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.sulithosting.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sulit Hosting
  introTitle: 
  introMessage: 
  navbar:
    - title: Billing Portal
      href: https://billing.sulithosting.com

user-agent: zbtechph

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
